### ISSUE TITLE
Turkish diacritics

### ISSUE THREAD

**Issue by MonsterMMORPG** [diacritics/database#15]
Ş > S
ş > s
Ç > C
ç > c
Ğ > G
ğ > g
Ü > U
ü > u
İ > I
ı > i
Ö > O
ö > o

In Turkish however, diacritics changes the meaning of words unlike in Arabic

**Comment by Mottie** [comment]
Awesome thank you!

Those are the base characters, correct? I am guessing the letters don't decompose into anything (e.g. in German, the diacritic `ü` has a base of `u` and decomposes into `ue`)?

**Comment by MonsterMMORPG** [comment]
@Mottie well i don't know such decomposition. also in Turkish they are standalone characters not additions :)

**Comment by Mottie** [comment]
See PR #16 which includes this file and many others.

**Comment by Mottie** [comment]
@MonsterMMORPG The extract method also includes an Arabic language file, but the method being using could only find 5 diacritics (ref: [`ar.js`](https://github.com/diacritics/database/blob/extract/src/ar/ar.js)); you shared a list of 8 with me in Gitter. If you have time, would you please check them?

**Comment by MonsterMMORPG** [comment]
@Mottie i strip these as diacritics

 "َ", "ً", "ُ", "ٌ", "ِ", "ٍ", "ْ", "َ"

there are also 2 other diacritics which i dont strip because they change the meaning of the word

أ the upper part of that letter
""ّ

I dont know arabic very well though 

you can get a lot more help from this guy : https://github.com/linuxscout/arramooz

**Comment by Mottie** [comment]
Hmm, on this [Turkish keyboard](http://turkish.typeit.org/), there are a few extra diacritics...

`âîû ÂÎÛ` 

The [unicode reference](http://www.unicode.org/cldr/charts/latest/by_type/core_data.alphabetic_information.main.html) doesn't include the above characters in the alphabet:

```
a b c ç d e f g ğ h i I İ ı j k l m n o ö p r s ş t u ü v y z 
```

And [wikipedia reports](https://en.wikipedia.org/wiki/Turkish_language#Writing_system):

> A circumflex is written over back vowels following ⟨k⟩, ⟨g⟩, or ⟨l⟩ when these consonants represent [c], [ɟ], and [l]—almost exclusively in Arabic and Persian loans.

Which is somewhat vague... so, should these diacritics be included?

**Comment by MonsterMMORPG** [comment]
@Mottie yes those are Turkish (perhaps from Ottoman Turkish) as well but we i have never typed them actually :D And my keyboard even doesnt have them. Only used them by auto correction of Microsoft Word several times. 

You can add those too i guess
