### ISSUE TITLE
Case Sensitive / Capital Characters

### ISSUE THREAD

**Issue by julkue** [diacritics/database#27]
Currently we have an output like e.g.:

```javascript
"ü": {
  "mapping": {
    "base": "u",
    "decompose": {
      "titleCase": "Ue",
      "upperCase": "UE",
      "lowerCase": "ue"
    }
  }
},
```

In order to keep the behavior of [mark.js' regular expression creation](https://github.com/julmot/mark.js/blob/31ae60c099bf82539079add9a3fe76fbc079b5dd/src/lib/regexpcreator.js#L288) we need to differentiate between capital and non-capital characters. For above mentioned example I could imagine an output like:

```javascript
"ü": {
  "capital": false,
  "mapping": {
    "base": "u",
    "decompose": {
      "lowerCase": "ue"
    }
  }
}
```

So, a new property `capital` was added and `titleCase` as well as `upperCase` was removed. For the opposite -- the capital character:

```javascrpit
"Ü": {
  "mapping": {
    "base": "U",
    "decompose": {
      "titleCase": "Ue",
      "upperCase": "UE",
      "lowerCase": "ue"
    }
  },
}
```
it could be:
```javascrpit
"Ü": {
  "capital": true,
  "mapping": {
    "base": "U",
    "decompose": {
      "titleCase": "Ue",
      "upperCase": "UE"
    }
  },
}
```

What do you think @Mottie?

Btw.: I've noticed that the equivalents generation is inconsistent. We have always used camelCase (e.g. `"languageNative"`) but in the equivalents part we have e.g. `html_decimal`.

**Comment by Mottie** [comment]
Adding a `capital` value would be a good addition; but I think it would be better to include all decompose values in case the user is switching the case of the character.

I'll update the database to use camel-cased keys.

**Comment by julkue** [comment]
>  but I think it would be better to include all decompose values in case the user is switching the case of the character.

Could you please elaborate this use case bit?

**Comment by Mottie** [comment]
I know the value could be converted to the desired case before accessing the database, but we don't really know the use-case of the database yet. If a developer wants to get the data for `ü`, but wants the output to be all caps we should have an `upperCase` value available.

**Comment by julkue** [comment]
@Mottie From my point of view we're currently doing everything that is necessary to get mark.js rolled out with the diacritics integration. If we do not have use cases for keeping `upperCase` and it won't be included in the node module I don't see a reason to keep it?

**Comment by Mottie** [comment]
What do we do about `es` characters like `¿` which has the same decompose title, upper and lower case value of `?`? There is no case.

Edit: I set these as lower case and removed the title and uppercase entries.

**Comment by Mottie** [comment]
Please review.
