### ISSUE TITLE
Add missing diacritics for consistency with mark.js

### ISSUE THREAD

**Issue by julkue** [diacritics/database#28]
mark.js offers much more diacritics than we have currently:

https://github.com/julmot/mark.js/blob/31ae60c099bf82539079add9a3fe76fbc079b5dd/src/lib/regexpcreator.js#L288

We should add them into the project.

**Comment by Mottie** [comment]
These categorized diacritics could be added to an "und" locale; it goes along with how Unicode defines [undetermined language as "und"](http://www.unicode.org/reports/tr35/#Unknown_or_Invalid_Identifiers). 

I [mentioned](https://github.com/diacritics/database/issues/1#issuecomment-264853479) something similar in the past; but suggested including a much broader range of characters. I now think it would be better to start with mark.js' current list of replacements and use it to build an "und" entry. The main question is should it include all those diacritics, or just the diacritics that aren't associated with a locale in the database?

**Comment by julkue** [comment]
So you mean not determining where the diacritics come from and creating the corresponding files, instead pasting them all into a container for undefined diacritics?

If so I'd prefer the first way, trying to classifying the diacritics.
